package com.zmijewski.ecommerce.model.enums;

import com.zmijewski.ecommerce.model.entity.GlobalParameter;

public enum GlobalParameterName {
    REGISTRATION_URL,
    REDIRECT_ONLINE_PAYMENT_URL,
    REDIRECT_CANCEL_ONLINE_PAYMENT_URL,
    CHECK_ORDER_URL,
    ORDER_STATUS_CREATED_MESSAGE,
    ORDER_STATUS_PAYED_MESSAGE,
    ORDER_STATUS_IN_DELIVERY_MESSAGE,
    ORDER_STATUS_DELIVERED_MESSAGE,
    ORDER_STATUS_PROCESSING_MESSAGE,
    ORDER_STATUS_WAITING_FOR_PAYMENT_MESSAGE,
    ORDER_STATUS_CANCELLED_MESSAGE,
    ORDER_STATUS_RETURNED_MESSAGE,
    INFORM_USER_ORDER_EXPIRE_IN_DAYS,
    AUDIT_LOG_BRAND_PERSIST_MESSAGE,
    AUDIT_LOG_BRAND_UPDATE_MESSAGE,
    AUDIT_LOG_BRAND_DELETE_MESSAGE,
    AUDIT_LOG_CATEGORY_PERSIST_MESSAGE,
    AUDIT_LOG_CATEGORY_UPDATE_MESSAGE,
    AUDIT_LOG_CATEGORY_DELETE_MESSAGE,
    AUDIT_LOG_PAYMENT_PERSIST_MESSAGE,
    AUDIT_LOG_PAYMENT_UPDATE_MESSAGE,
    AUDIT_LOG_PAYMENT_DELETE_MESSAGE,
    AUDIT_LOG_PRODUCT_PERSIST_MESSAGE,
    AUDIT_LOG_PRODUCT_UPDATE_MESSAGE,
    AUDIT_LOG_PRODUCT_DELETE_MESSAGE,
    AUDIT_LOG_SHIPPING_PERSIST_MESSAGE,
    AUDIT_LOG_SHIPPING_UPDATE_MESSAGE,
    AUDIT_LOG_SHIPPING_DELETE_MESSAGE,
    AUDIT_LOG_USER_PERSIST_MESSAGE,
    AUDIT_LOG_USER_UPDATE_MESSAGE,
    AUDIT_LOG_USER_DELETE_MESSAGE
}
