package com.zmijewski.ecommerce.model.enums;

public enum GlobalParameterName {
    REGISTRATION_URL,
    REDIRECT_ONLINE_PAYMENT_URL,
    REDIRECT_CANCEL_ONLINE_PAYMENT_URL,
    CHECK_ORDER_URL,
    ORDER_STATUS_CREATED_MESSAGE,
    ORDER_STATUS_PAYED_MESSAGE,
    ORDER_STATUS_IN_DELIVERY_MESSAGE,
    ORDER_STATUS_DELIVERED_MESSAGE,
    ORDER_STATUS_PROCESSING_MESSAGE,
    ORDER_STATUS_WAITING_FOR_PAYMENT_MESSAGE,
    ORDER_STATUS_CANCELLED_MESSAGE,
    ORDER_STATUS_RETURNED_MESSAGE,
    INFORM_USER_ORDER_EXPIRE_IN_DAYS,
}
